services:

  server:
    build: ./server/bin
    container_name: serv
    environment:
      - HUG_API=""
    ports:
      - 12345:12345
    volumes:
      - ./server/bin:/opt/serv


  client1:
    build: ./client/bin
    command: /bin/bash /opt/client/main
    depends_on:
      - server
    volumes:
      - ./client/bin:/opt/client

  client2:
    build: ./client/bin
    command: /bin/bash /opt/client/main
    depends_on:
      - server
    volumes:
      - ./client/bin:/opt/client

  client3:
    build: ./client/bin
    command: /bin/bash /opt/client/main
    depends_on:
      - server
    volumes:
      - ./client/bin:/opt/client

  client4:
    build: ./client/bin
    command: /bin/bash /opt/client/main
    depends_on:
      - server
    volumes:
      - ./client/bin:/opt/client

  client5:
    build: ./client/bin
    command: /bin/bash /opt/client/main
    depends_on:
      - server
    volumes:
      - ./client/bin:/opt/client
